name: build

on: [push]

jobs:
  build:
    name: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install, lint and test
      shell: bash
      run: |
        npm ci
        npm run lint
        npm run test-once
      env:
        CI: true
